;;; org-noter-pdftools-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-noter-pdftools.el

(register-definition-prefixes "org-noter-pdftools" '("org-noter-pdftools-"))

;;; End of scraped data

(provide 'org-noter-pdftools-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-noter-pdftools-autoloads.el ends here
