;;; ob-hy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ob-hy.el

(register-definition-prefixes "ob-hy" '("main" "org-babel-"))


;;; Generated autoloads from test-ob-hy.el

(register-definition-prefixes "test-ob-hy" '("ob-hy-test-" "org-"))

;;; End of scraped data

(provide 'ob-hy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ob-hy-autoloads.el ends here
