;;; wolfram-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from wolfram.el

(autoload 'wolfram-alpha "wolfram" "\
Sends a query to Wolfram Alpha, returns the resulting data as a list of pods.

(fn QUERY)" t)
(autoload 'wolfram-alpha-navigate-to-category "wolfram" "\
Display a navigable menu of all categories (headings) in the current WolframAlpha buffer." t)
(register-definition-prefixes "wolfram" '("wolfram-"))

;;; End of scraped data

(provide 'wolfram-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wolfram-autoloads.el ends here
