;;; poly-markdown-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from poly-markdown.el

 (autoload 'poly-markdown-mode "poly-markdown")
(add-to-list 'auto-mode-alist '("\\.md\\'" . poly-markdown-mode))
 (autoload 'poly-gfm-mode "poly-markdown")
(register-definition-prefixes "poly-markdown" '("poly-"))

;;; End of scraped data

(provide 'poly-markdown-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; poly-markdown-autoloads.el ends here
