;;; hy-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hy-base.el

(register-definition-prefixes "hy-base" '("hy--"))


;;; Generated autoloads from hy-font-lock.el

(register-definition-prefixes "hy-font-lock" '("hy-font-lock-" "inferior-hy-font-lock-kwds"))


;;; Generated autoloads from hy-jedhy.el

(autoload 'run-jedhy "hy-jedhy" "\
Startup internal Hy interpreter process, enabling jedhy for `company-mode'." t)
(register-definition-prefixes "hy-jedhy" '("company-hy" "hy-" "run-jedhy--pyvenv-post-deactive-hook"))


;;; Generated autoloads from hy-mode.el

(add-to-list 'auto-mode-alist '("\\.hy\\'" . hy-mode))
(add-to-list 'interpreter-mode-alist '("hy" . hy-mode))
(autoload 'hy-mode "hy-mode" "\
Major mode for editing Hy files.

(fn)" t)
(autoload 'hy-insert-pdb "hy-mode" "\
Import and set pdb trace at point." t)
(register-definition-prefixes "hy-mode" '("hy-" "inferior-hy-mode-syntax-table"))


;;; Generated autoloads from hy-shell.el

(autoload 'inferior-hy-mode "hy-shell" "\
Major mode for Hy inferior process.

(fn)" t)
(autoload 'run-hy "hy-shell" "\
Startup and/or switch to a Hy interpreter process." t)
(register-definition-prefixes "hy-shell" '("hy-"))


;;; End of scraped data

(provide 'hy-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hy-mode-autoloads.el ends here
