;;; tab-jump-out-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tab-jump-out.el

(autoload 'tab-jump-out "tab-jump-out" "\
Use tab to jump out." t)
(autoload 'tab-jump-out-mode "tab-jump-out" "\
A minor mode that allows you to jump out with tab.

This is a minor mode.  If called interactively, toggle the
`Tab-Jump-Out mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `tab-jump-out-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

\\{tab-jump-out-mode-map}

(fn &optional ARG)" t)
(put 'tab-jump-out-global-mode 'globalized-minor-mode t)
(defvar tab-jump-out-global-mode nil "\
Non-nil if Tab-Jump-Out-Global mode is enabled.
See the `tab-jump-out-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `tab-jump-out-global-mode'.")
(custom-autoload 'tab-jump-out-global-mode "tab-jump-out" nil)
(autoload 'tab-jump-out-global-mode "tab-jump-out" "\
Toggle Tab-Jump-Out mode in all buffers.
With prefix ARG, enable Tab-Jump-Out-Global mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Tab-Jump-Out mode is enabled in all buffers where `(lambda nil
(tab-jump-out-mode 1))' would do it.

See `tab-jump-out-mode' for more information on Tab-Jump-Out mode.

(fn &optional ARG)" t)
(register-definition-prefixes "tab-jump-out" '("tab-jump-out-"))

;;; End of scraped data

(provide 'tab-jump-out-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tab-jump-out-autoloads.el ends here
