;;; major-mode-hydra-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from major-mode-hydra.el

(autoload 'major-mode-hydra-define "major-mode-hydra" "\
Generate a major mode hydra for given MODE with given BODY and HEADS-PLIST.
Overwrite existing hydra if there is one.

MODE can also be a list of modes in which case the same hydras
are created for all these modes.  Useful in multiple closely
related major modes.

Refer to `pretty-hydra-define' for documentation about BODY and HEADS-PLIST.

(fn MODE BODY HEADS-PLIST)" nil t)
(function-put 'major-mode-hydra-define 'lisp-indent-function 'defun)
(autoload 'major-mode-hydra-define+ "major-mode-hydra" "\
Generate a major mode hydra for given MODE with given BODY and HEADS-PLIST.
Add new heads if there is already an existing one.

MODE can also be a list of modes in which case the same hydras
are created for all these modes.  Useful in multiple closely
related major modes.

Refer to `pretty-hydra-define' for documentation about BODY and HEADS-PLIST.

(fn MODE BODY HEADS-PLIST)" nil t)
(function-put 'major-mode-hydra-define+ 'lisp-indent-function 'defun)
(autoload 'major-mode-hydra-bind "major-mode-hydra" "\
Add BINDINGS (heads) for a MODE under the COLUMN.

MODE is the major mode name (symbol).  There is no need to quote it.

COLUMN is a string to put the hydra heads under.

BINDINGS is a list of hydra heads to be added.  Each head has
exactly the same structure as that in `pretty-hydra-define' or
`defhydra', except `:exit' is set to t by default.

(fn MODE COLUMN &rest BINDINGS)" nil t)
(function-put 'major-mode-hydra-bind 'lisp-indent-function 2)
(make-obsolete 'major-mode-hydra-bind 'major-mode-hydra-define+ "July 2019")
(autoload 'major-mode-hydra "major-mode-hydra" "\
Show the hydra for the current major mode." t)
(register-definition-prefixes "major-mode-hydra" '("major-mode-hydra-"))

;;; End of scraped data

(provide 'major-mode-hydra-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; major-mode-hydra-autoloads.el ends here
