;;; maxima-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from maxima.el

(autoload 'maxima-mode "maxima" "\


(fn)" t)
(autoload 'maxima-remove-inferior "maxima" "\
Remove the INFERIOR-PROCESS and the process buffer.

(fn INFERIOR-PROCESS)" nil t)
(autoload 'maxima-start "maxima" "\
Start a maxima process and save the process in INFERIOR-SYMBOL.
The process name is passed in NAME.

(fn INFERIOR-SYMBOL NAME)" nil t)
(autoload 'maxima "maxima" "\
Run Maxima interactively inside a buffer." t)
(put 'global-maxima-minor-mode 'globalized-minor-mode t)
(defvar global-maxima-minor-mode nil "\
Non-nil if Global Maxima minor mode is enabled.
See the `global-maxima-minor-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-maxima-minor-mode'.")
(custom-autoload 'global-maxima-minor-mode "maxima" nil)
(autoload 'global-maxima-minor-mode "maxima" "\
Toggle Maxima minor mode in all buffers.
With prefix ARG, enable Global Maxima minor mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Maxima minor mode is enabled in all buffers where `maxima-minor-mode'
would do it.

See `maxima-minor-mode' for more information on Maxima minor mode.

(fn &optional ARG)" t)
(register-definition-prefixes "maxima" '("maxima-"))


;;; Generated autoloads from maxima-font-lock.el

(register-definition-prefixes "maxima-font-lock" '("maxima-font-lock-"))

;;; End of scraped data

(provide 'maxima-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; maxima-autoloads.el ends here
