;;; math-symbol-lists-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from math-symbol-lists.el

(register-definition-prefixes "math-symbol-lists" '("math-symbol-list-"))


;;; Generated autoloads from msl-build.el

(register-definition-prefixes "msl-build" '("msl-"))

;;; End of scraped data

(provide 'math-symbol-lists-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; math-symbol-lists-autoloads.el ends here
