;;; vterm-toggle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vterm-toggle.el

(autoload 'vterm-toggle "vterm-toggle" "\
Vterm toggle.
Optional argument ARGS .

(fn &optional ARGS)" t)
(autoload 'vterm-toggle-cd "vterm-toggle" "\
Vterm toggle and insert a cd command.
Optional argument ARGS .

(fn &optional ARGS)" t)
(autoload 'vterm-toggle-insert-cd "vterm-toggle" "\
Cd to the directory where your previous buffer file exists.
after you have toggle to the vterm buffer with `vterm-toggle'." t)
(autoload 'vterm-toggle-forward "vterm-toggle" "\
Go to the next term buffer.
If OFFSET is `non-nil', will goto next term buffer with OFFSET.

(fn &optional OFFSET)" t)
(autoload 'vterm-toggle-backward "vterm-toggle" "\
Go to the previous term buffer.
If OFFSET is `non-nil', will goto next term buffer with OFFSET.

(fn &optional OFFSET)" t)
(register-definition-prefixes "vterm-toggle" '("vterm-"))

;;; End of scraped data

(provide 'vterm-toggle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vterm-toggle-autoloads.el ends here
