;;; all-the-icons-ivy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from all-the-icons-ivy.el

(autoload 'all-the-icons-ivy-setup "all-the-icons-ivy" "\
Set ivy's display transformers to show relevant icons next to the candidates.")
(register-definition-prefixes "all-the-icons-ivy" '("all-the-icons-"))

;;; End of scraped data

(provide 'all-the-icons-ivy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; all-the-icons-ivy-autoloads.el ends here
