;;; python-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from python-mode.el

(register-definition-prefixes "python-mode" '("all-mode-setting" "comint-mime-" "flake8" "force-py-shell-name-p-o" "gud-pdb-history" "highlight-indent-active" "hs-hide-comments-when-hiding-all" "info-lookup-mode" "ipython" "iypthon" "jython" "pdb-track-stack-from-shell-p" "pep8" "pst-here" "quote" "strip-chars-" "toggle-force-py-shell-name-p" "turn-o" "virtualenv-"))

;;; End of scraped data

(provide 'python-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; python-mode-autoloads.el ends here
