;;; julia-formatter-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from julia-formatter.el

(autoload 'julia-formatter-compile-image "julia-formatter" "\
Pull up a buffer to compile image.

Returns t." t)
(autoload 'julia-formatter-format-region "julia-formatter" "\
Format region delimited by BEGIN and END  using JuliaFormatter.jl.

Region must have self-contained code.  If not, the region won't be formatted and
will remain as-is.

(fn BEGIN END)")
(autoload 'julia-formatter-beginning-of-defun "julia-formatter" "\
Get beginning of surrounding debufn from `julia-formatter--defun-range'.

Move to the ARG -th beginning of defun.

(fn &optional (ARG 1))")
(autoload 'julia-formatter-end-of-defun "julia-formatter" "\
Get beginning of surrounding debufn from `julia-formatter--defun-range'.

See `end-of-defun-function' to understand values of ARG.

(fn &optional (ARG 1))")
(autoload 'julia-formatter-format-buffer "julia-formatter" "\
Format the whole buffer.")
(autoload 'julia-formatter-mode "julia-formatter" "\
Setup buffer for formatting code using indenting functions.

See documentation on `indent-region-function' for different ways you can indent
current buffer (by line, by region, whole buffer ...)

When `julia-formatter-setup-for-save' is non-nil, will format buffer before
saving.

This is a minor mode.  If called interactively, toggle the
`Julia-Formatter mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `julia-formatter-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "julia-formatter" '("hash-equal" "julia-formatter-"))


;;; Generated autoloads from toml-respects-json.el

(register-definition-prefixes "toml-respects-json" '("toml-respects-json"))

;;; End of scraped data

(provide 'julia-formatter-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; julia-formatter-autoloads.el ends here
