;;; ebuku-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ebuku.el

(autoload 'ebuku-mode "ebuku" "\
Major mode for interacting with the buku bookmark manager.

\\{ebuku-mode-map}

(fn)" t)
(autoload 'ebuku "ebuku" "\
Start Ebuku, an interface to the buku bookmark manager." t)
(register-definition-prefixes "ebuku" '("ebuku-"))

;;; End of scraped data

(provide 'ebuku-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ebuku-autoloads.el ends here
