;;; poly-noweb-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from poly-noweb.el

 (autoload 'poly-noweb-mode "poly-noweb")
(add-to-list 'auto-mode-alist '("\\.nw\\'" . poly-noweb-mode))
(register-definition-prefixes "poly-noweb" '("noweb-code-mode" "poly-noweb-"))

;;; End of scraped data

(provide 'poly-noweb-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; poly-noweb-autoloads.el ends here
