;;; zetteldesk-remark-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from zetteldesk-remark.el

(defvar zetteldesk-remark-mode nil "\
Non-nil if zetteldesk-remark mode is enabled.
See the `zetteldesk-remark-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `zetteldesk-remark-mode'.")
(custom-autoload 'zetteldesk-remark-mode "zetteldesk-remark" nil)
(autoload 'zetteldesk-remark-mode "zetteldesk-remark" "\
Toggle the `zetteldesk-remark-mode'.

This mode initialises the value of `zetteldesk-remark-title', an
important variable for using org-remark in buffers not associated
to a file.

This is a global minor mode.  If called interactively, toggle the
`zetteldesk-remark mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='zetteldesk-remark-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "zetteldesk-remark" '("zetteldesk-remark-"))

;;; End of scraped data

(provide 'zetteldesk-remark-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; zetteldesk-remark-autoloads.el ends here
