;;; git-timemachine-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from git-timemachine.el

(autoload 'git-timemachine-toggle "git-timemachine" "\
Toggle git timemachine mode." t)
(autoload 'git-timemachine "git-timemachine" "\
Enable git timemachine for file of current buffer." t)
(autoload 'git-timemachine-switch-branch "git-timemachine" "\
Enable git timemachine for current buffer, switching to GIT-BRANCH.

(fn GIT-BRANCH)" t)
(register-definition-prefixes "git-timemachine" '("git-timemachine-"))

;;; End of scraped data

(provide 'git-timemachine-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; git-timemachine-autoloads.el ends here
